services:
  api:
    build:
      context: ../../
      dockerfile: code/deployment/api/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ../../code/deployment/api:/app/code/deployment/api
      - ../../code/deployment/app:/app/code/deployment/app
      - ../../code/models:/app/code/models
      - ../../data:/app/data
      - ../../models:/app/models
    networks:
      - app-network

  app:
    build:
      context: ../../
      dockerfile: code/deployment/app/Dockerfile.app
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ../../code/deployment/api:/app/code/deployment/api
      - ../../code/deployment/app:/app/code/deployment/app
      - ../../code/models:/app/code/models
      - ../../data:/app/data
      - ../../models:/app/models
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
